### ISSUE TITLE
NationalMap - print preview broken 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1141] opened 2022-04-18 23:42 UTC
when testing latest version of NationalMap https://staging.nm.terria.io/, clicking on Print preview triggers white screen.

**Comment by steve9164** [comment] 2022-04-19 04:27
No one's assigned to this, so I'll investigate and report back on what the problem is.

**Comment by steve9164** [comment] 2022-04-22 06:13
Fixed by https://github.com/TerriaJS/terriajs/pull/6257

**Closed by steve9164** 2022-04-22 06:13 UTC
Labels: bug
