### ISSUE TITLE
National Map v2017-07-21 pre-release test - Layer asking for authentication

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#554] opened 2017-07-28 04:48 UTC
Layer: Local Government/Western Australia/Wanneroo/Drainage Nodes Wanneroo (WAN-002)

- Prompted for 'Authentication' (see Slide 32)
- Cancel generated error (see Slide 33)
- The error has not be cleared (trapped), reappeared after opening the Add Data - without clicking any layer name or add to map buttons (see Slide 34)

![slide32](https://user-images.githubusercontent.com/22827786/28702905-a1265de4-73a3-11e7-9516-e7afbb280123.JPG)
![slide33](https://user-images.githubusercontent.com/22827786/28702903-a118b1c6-73a3-11e7-9417-295a4efde725.JPG)
![slide34](https://user-images.githubusercontent.com/22827786/28702904-a11d89ee-73a3-11e7-974f-57d43964e301.JPG)

**Comment by ajbar7** [comment] 2017-08-10 04:38
@EhsanCanberra has this been an error on any other WA layers?

@kring / @steve9164 - assume the error is being generated because the preview is trying to load the layer.

I've written to data.wa peeps to see if there's anything in their catalogue that will tell us a layer requires auth.

**Comment by keithmoss** [comment] 2017-08-10 05:05
Hi folks,

If the WMS/WFS/ESRI Service URL:

- Comes from the services.slip.wa.gov.au domain,
- Contains the string "_Public_", and
- The resource/directory part of the URL begins with "/public/".

Then it won't require authentication.

e.g. https://services.slip.wa.gov.au**/public/**rest/services/CityofPerth**_Public_**Services/CityofPerth_Public_Services/MapServer

Steven Bennett added a similar check to NationalMap for the State Government layers when he was at Data61.

**Comment by QuadTog** [comment] 2018-04-20 01:57
@keithmoss @kring 

What if a Service URL comes from services.slip.wa.gov.au but is Private/Subscription?

I have an account on SLIP, but when I try and access certain data-sets from services.wa.gov.au (via NationalMap) I repeatedly get prompted for login info from NationalMap. I assume this is actually a login request for SLIP but routed through NationalMap. 

Regardless of if it's entered correctly or not though, the login window repeatedly prompts me. I assume this is because SLIP hasn't internally granted me access to these data-sets so it gets stuck on a login request loop.

Is there a way for SLIP to return a response if my login info is correct but I don't have access to the data?

**Comment by keithmoss** [comment] 2018-04-20 07:12
@QuadTog It looks like the NationaMap proxy isn't passing the credentials you provide back to us - or at least not using the right method.

To your other question - Unfortunately we can't currently return a response that's "Authorisation OK, but you lack access" in way that would be usable by services like NationalMap.

If you've got a use case for that feature I'll happily pop it into our feedback log. We don't need a lot - just a paragraph or two about how you would use it, how it would benefit you, and/or how it would make your work more efficient.

@kring When a user provides credentials to `http://nationalmap.gov.au/proxy` how are they passed back to the service being proxied?

**Comment by keithmoss** [comment] 2018-04-23 01:29
Good to know, ta @EhsanCanberra. What's the estimated release date?

**Comment by QuadTog** [comment] 2018-04-23 06:54
@keithmoss It looks like the issue is actually NationalMap not passing any credentials through.

**Use Case**

> Currently any login request passed through NationalMap appears as originating from NationalMap and doesn't pass credentials through. This causes issues when users try to access restricted data as they cannot login into restricted data nor determine which data source they're trying to access.
> 
> Without this function, users cannot access **any** restricted data via NationalMap. This is causing a reasonable amount of tickets to build up both requesting help on this matter and/or access to this data.

**Comment by steve9164** [comment] 2018-04-26 04:52
@QuadTog @keithmoss The proxy service code is hosted [here](https://github.com/TerriaJS/terriajs-server/blob/master/lib/controllers/proxy.js#L65:22). It looks like the request headers should be passed through to the proxied service (unless the service has it's own authorization header stored by terriajs-server). That depends on the response by the map server (and how terriajs-server proxy deals with that) when an unauthenticated request is made (like basic auth flow, etc.).

Not sure if/how much that helps.

**Comment by keithmoss** [comment] 2018-06-19 00:46
@steve9164 Just opened #766. It seems whatever was changed that fixed the original issue in v2018-04-16 has broken passing authentication details to secured layers.

Let us know if there's any help you need from our side to resolve this.

**Comment by AnaBelgun** [comment] 2018-06-22 06:09
Will be fixed in July 2018 release: https://github.com/TerriaJS/nationalmap/issues/766

**Closed by AnaBelgun** 2018-06-22 06:09 UTC
Labels: GA-testing
